config/routes.rb
Store15::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

end

Spree::Core::Engine.routes do
  namespace :admin do
    resources :providers
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

  checkout_flow do
    go_to_state :address, :if => lambda { |order| order.address_required? }
    go_to_state :payment, :if => lambda { |order| order.payment_required? }
    go_to_state :confirm
    go_to_state :complete
  end

  def address_required?
    return false
  end

  # If true, causes the payment step to happen during the checkout process
  def payment_required?
    return false
  end

  # If true, causes the confirmation step to happen during the checkout process
  def confirmation_required?
    return true
  end

end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  belongs_to :provider
end

app/models/spree/provider.rb
module Spree
  class Provider < Spree::Base
    has_many :spree_products, :class_name => 'Spree::Product'
    validates :name, :tel, presence: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do

  before_filter :load_providers

  def load_providers
    @providers = Spree::Provider.all
  end

end

app/controllers/spree/admin/providers_controller.rb
module Spree
  module Admin
    class ProvidersController < ResourceController

      def index
        respond_with(@collection)
      end

      private

      def collection
        return @collection if @collection.present?
        # params[:q] can be blank upon pagination
        params[:q] = {} if params[:q].blank?

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
          page(params[:page]).
          per(Spree::Config[:properties_per_page])
        @collection
      end

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store15</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/admin/providers/_form.html.erb
<div data-hook="admin_provider_form" class="align-center row">
  <div class="alpha eight columns">
    <%= f.field_container :name do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
      <%= f.text_field :name, :class => 'fullwidth' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div class="alpha eight columns">
    <%= f.field_container :tel do %>
      <%= f.label :tel, Spree.t(:tel) %> <span class="required">*</span><br />
      <%= f.text_field :tel, :class => 'fullwidth' %>
      <%= f.error_message_on :tel %>
    <% end %>
  </div>
  <div class="alpha eight columns">
    <%= f.field_container :address do %>
      <%= f.label :address, Spree.t(:address) %><br />
      <%= f.text_field :address, :class => 'fullwidth' %>
      <%= f.error_message_on :address %>
    <% end %>
  </div>
</div>

app/views/spree/admin/providers/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_provider) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= button_link_to Spree.t(:back_to_providers_list), admin_providers_url, :icon => 'arrow-left'%></li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @provider } %>

<%= form_for [:admin, @provider] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/providers/filtered.html.erb
<%= auto_complete_result @providers, :name %>

app/views/spree/admin/providers/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:providers) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_provider_link">
    <%= button_link_to Spree.t(:new_provider), new_admin_provider_url, { :remote => true, :icon => 'plus', 'data-update' => 'new_provider', :id => 'new_provider_link' } %>
  </li>
<% end %>

<%= render 'spree/admin/shared/product_sub_menu' %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_provider_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {:f => f} %>
      <div data-hook="admin_provider_index_search">
        <div class="alpha eight columns">
          <div class="field">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, :size => 15 %>
          </div>
        </div>
      </div>
      <div class="clear"></div>
      <div class="form-buttons actions filter-actions" data-hook="admin_provider_index_search_buttons">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<div id="new_provider"></div>

<% if @providers.any? %>
  <table class="index" id='listing_providers' data-hook>
    <colgroup>
      <col style="width: 35%">
      <col style="width: 15%">
      <col style="width: 35%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="listing_providers_header">
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:tel) %></th>
        <th><%= Spree.t(:address) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @providers.each do |provider| %>
        <tr id="<%= spree_dom_id provider %>" data-hook="listing_providers_row" class="<%= cycle('odd', 'even')%>">
          <td style="padding-left:1em"><%= provider.name %></td>
          <td style="padding-left:1em"><%= provider.tel %></td>
          <td style="padding-left:1em"><%= provider.address %></td>
          <td class="actions">
            <%= link_to_edit(provider, :no_text => true) %>
            <%= link_to_delete(provider, :no_text => true) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/provider')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_provider_path %>!
  </div>
<% end %>

<%= paginate @collection %>

app/views/spree/admin/providers/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @provider } %>

<%= form_for [:admin, @provider] do |f| %>
  <fieldset data-hook="new_provider">
    <legend align="center"><%= Spree.t(:new_provider) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="filter-actions">
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/providers/new.js.erb
$("#new_provider").html('<%= escape_javascript(render :template => "spree/admin/providers/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_provider_link").parent().hide();